<!doctype html>
<title>fuEDF</title>
<style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Loved+by+the+King&subset=latin,latin-ext);
@import url(http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Sans+Mono);
@import url({{url_for('static', filename="style.css")}});
</style>
{% block jsinc %}{% endblock jsinc %}
<div id="main">
    <div id="title">
       <h1><a href="{{ url_for('index') }}">fuEDF</a></h1>
    </div>
    <div id="content">
        {% block body %}{% endblock %}
    </div>
    <div id="footer">(c) 2012 <a href="http://www.brahici.org">Brice Vissi&egrave;re</a>
        -- powered by <a href="http://flask.pocoo.org/">Flask</a>
    {% if g._show_coverage %}
        -- <a href="{{url_for('static', filename="htmlcov/index.html")}}" target="_blank">see coverage result</a>
    {% endif %}
    </div>
</div>
