<!doctype html>
<title>fuEDF</title>
<style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Loved+by+the+King&subset=latin,latin-ext);
@import url(http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Sans+Mono);
@import url({{url_for('static', filename="style.css")}});
</style>
{% block jsinc %}{% endblock jsinc %}
<div id="main">
    <div id="title">
       <h1><a href="{{ url_for('index') }}">fuEDF</a></h1>
    </div>
    <div id="content">
        {% block body %}{% endblock %}
    </div>
</div>

